### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#1]
So, there's a couple different camps on UX of login things.
1. A bar slides down on the top of the page, and offers to log in.
2. Login boxes are autofilled, and some animation is given to draw your attention
3. There is an icon for you to click to auto login (chrome browser actions)

Clef is different from a regular password manager, so I would like to find a way that is different from the competition.  My current idea is to have a semicircle slide in on one of the corners, and clicking that would bring up the (very well-designed) clef authentication overlay.

![screen shot 2013-08-14 at 3 27 58 pm](https://f.cloud.github.com/assets/657707/964899/0e9dd812-0520-11e3-839b-ae4f48b07b00.png)
_No, my facebook username is not ilikepillar123123.  That is my wife :)_

I don't love this, but I like it more than the other somewhat-boring options.  I am still refining this idea, and would love to get some feedback.

**Comment by jessepollak** [comment]
I think this has potential. A variant:

When a user hits a website that has a login form, we put a little animation of the Clef mark in the bottom right or left corner. On hover, it animates out into the full CLEF name and when they click the overlay comes down. This is a little more explicit than the semicircle, but it's also a bit more invasive. I do like the 'pending' feeling that the spinning animation brings — just waiting for a user to click on it and log in.

**Comment by josephwegner** [comment]
That sounds awesome!

I just pushed two branches, one with each UI.  If you get a chance, check them out and let me know your thoughts.  The colors on circleUI are definitely not final, but that's the idea anyways.

Neither of them have hover or click actions - that's for the train ride in the morning.

**Comment by jessepollak** [comment]
I like them both. Maybe we could mash them? Have the logo spinning on top of the circleUI? I think that a slower, more consistent spin would work better too.

**Comment by josephwegner** [comment]
Heh - the more I look at it, the more I think I like the one with just the logo better.  I'm going to build out the hover state (slide out LEF), and see how I feel then.

I also just realized that we need some sort of dismiss action.  Not quite sure what that will look like yet.

**Comment by josephwegner** [comment]
Apparently GMail doesn't like the stuff I'm doing with SVG :)

![screen shot 2013-08-16 at 8 53 22 am](https://f.cloud.github.com/assets/657707/975607/31577a4a-067c-11e3-876b-a0436bbca721.png)

Anyways, you can kind of see what I'm working on on the left side.  I've got the spinning logo in the bottom right, and on-hover it spins to the "C" position, and animates in a darker hit zone that is about 20% of the length.  Entering the logo through the dark hit zone will fill the center with some color/text that indicates dismissal.  Entering through the regular clef area will fill the center with some color/text that indicates logging in.

Here's a short screencast that gives a little of the feel: http://cl.ly/1Z3i1G0w0C1k (note: the center filling part isn't in yet).

I'm considering growing the logo as well, so that the hit zones are bigger.  I'll have to play with it and see how to do that without messing with the user's mouse intentions.

_By the way, that logo was super easy to recreate in SVG.  You guys may want to consider that as you redesign - opens up the potential for a lot of cool animations_

**Comment by josephwegner** [comment]
From: f9fedcc4d

The SVG stuff is done, and I actually think it's really cool.  There's animations for hover, focus login, focus dismiss, and submit - all of which I think are great.

Take a look, and let me know what you think.  I know you're on vacation, so I might just run with this if I don't hear back from you.  If you get back and don't like it, I'm sure we can easily switch.

**Comment by josephwegner** [comment]
From: 6ec89441426c5b28a7ca3fb1457249abd7083271

I added an options page to the extension, which pretty much just contains a login form.  This will allow you to play/dev with the extension offline.

**Comment by josephwegner** [comment]
I just realized that we need to have some UI for adding (editing, deleting) credentials.

If we want, we can leave a real UI out for the MVP, and just have CRUD functions on the options page..  But it's definitely a must-have for a real release.  Again, the industry standard is to have a bar slide in at the top of the page, but I'm inclined to try something different.  I just don't know what.

**Comment by josephwegner** [comment]
Seems like the UI/UX discussion is evolved to the point that this general thread doesn't make sense.  Closing.
