### ISSUE TITLE
Restructure clef.js file

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#10]
I don't like the clef_ format, what are thoughts on reorganizing this to a more OO format @josephwegner .

**Comment by josephwegner** [comment]
Heh, you're absolutely correct.  When I started that format I didn't realize I would have so many functions.

I will create a master ClefVault object and contain the rest of the functionality in that.

**Comment by jessepollak** [comment]
Go with Vault (rather than ClefVault).

**Comment by josephwegner** [comment]
I prefer ClefVault..  Vault is pretty generic, and has a pretty high likelihood of overlapping with other JS that may be on the page.  That clef.js file gets injected directly into the page - I'd hate for it to break some site's login form.

**Comment by jessepollak** [comment]
Fair enough.

**Comment by jessepollak** [comment]
This is better, closing.
