### ISSUE TITLE
Add some more sites

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#117]
- [x] netflix
- [ ] hbo go
- [ ] hulu
- [ ] comcast

**Comment by iamb55** [comment]
- [x] Dropbox
- [ ] PRWeb

**Comment by iamb55** [comment]
- [ ] New York Times
- [ ] Wall Street Journal

**Comment by iamb55** [comment]
- [ ] icloud

**Comment by iamb55** [comment]
- [ ] The Economist
- [ ] Open Table
- [ ] Adobe (maybe we should focus on recent breaches and do Evernote, etc. too?)
- [ ] United Airlines (other airlines / portals?)

**Comment by jessepollak** [comment]
utdol.com
nytimes.com
bankofthewest.com
ally.com
kp.org
mozy.com
ceridian.com
cigna.com
yelp.com
bankofamerica.com
amion.com

**Comment by jessepollak** [comment]
imgur.com

**Comment by iamb55** [comment]
- [x] khanacademy.org
- [x] instapaper.com
- [ ] toggl.com
- [ ] simple.com
- [ ] expedia.com
- [ ] yahoo.com

**Comment by iamb55** [comment]
- [ ] redbox.com

**Comment by iamb55** [comment]
- [ ] login.microsoftonline.com
- [ ] icloud.com

**Comment by iamb55** [comment]
- [ ] capitalone.com

**Comment by iamb55** [comment]
- [ ] tes.co.uk
- [ ] grandst.com

**Comment by iamb55** [comment]
- [ ] landmarkcu.com

**Comment by iamb55** [comment]
- [ ] moz.com

**Comment by jessepollak** [comment]
- [ ] my.studiopress.com

**Comment by jessepollak** [comment]
- [ ] www.vcbonline.com

**Comment by iamb55** [comment]
- [ ] mailchimp.com

**Comment by jessepollak** [comment]
- [ ] americanexpress.com

**Comment by jessepollak** [comment]
- [ ] udemy

**Comment by jessepollak** [comment]
okcupid.com

**Comment by jessepollak** [comment]
accounts.planningcenteronline.com

**Comment by jessepollak** [comment]
mc.doridian.de

**Comment by josephwegner** [comment]
- [ ] live.yodle.com

**Comment by jessepollak** [comment]
- [ ] www.twitch.tv
- [x] bible.com

**Comment by jessepollak** [comment]
- [ ] chase.com

**Comment by jessepollak** [comment]
- [ ] startups.in

**Comment by iamb55** [comment]
- [ ] zipcar.com

**Comment by iamb55** [comment]
- [ ] shibboleth.nyu.edu

**Comment by jessepollak** [comment]
- [x] getpocket.com

**Comment by jessepollak** [comment]
- [ ] vimeo.com

**Comment by jessepollak** [comment]
- [ ] escalus.expensys.com

**Comment by jessepollak** [comment]
- [ ] login.live.com

**Comment by jessepollak** [comment]
- [ ] sfpl.lib.overdrive.com

**Comment by jessepollak** [comment]
- [x] instructables.com
- [x] codecademy.com
- [ ] box.com
- [ ] mint.com

**Comment by jessepollak** [comment]
- [ ] www.firstib.com
- [ ] evernote.com

**Comment by jessepollak** [comment]
- [ ] http://series.ly/

**Comment by jessepollak** [comment]
- [ ] www.lynda.com
- [ ] www.uno-e.com
- [ ] http://www.aerolineas.com.ar/
- [ ] http://whois.com
- [ ] http://copy.com
- [ ] http://outlook.com
- [ ] www.edreams.com.ar
- [x] http://instagram.com
- [ ] www.canva.com
- [ ] payza.com
- [ ] http://www.edmodo.com/
- [ ] quickbooks.com
- [ ] footholds.net
- [ ] vidahost.com
- [ ] bizcrowd.com
- [ ] discovercard.com
- [ ] bancomer.com.mx
- [ ] scottrade.com
- [ ] freeagent.com
- [ ] ups.com
- [ ] zendesk.com
- [ ] digitalocean.com
- [ ] weebly.com
- [ ] startimes.com
- [ ] dofus.com
- [ ] chatrwireless.com
- [ ] airmiles.ca
- [ ] safeway.com
- [ ] fortisbc.com
- [ ] bchydro.com
- [ ] sammobile.com
- [ ] balancefin.com
- [ ] tamaracinc.com
- [ ] mail.com
- [ ] paperlesspost.com
- [ ] manilla.com
- [ ] nhl.com
- [ ] roboform.com
- [ ] dixonsca.com
- [ ] graze.com
- [ ] fasthosts.co.uk
- [ ] webmail.sinopecservice-ec.com
- [ ] dominos.com
- [ ] usaa.com
- [ ] login.yahoo.co.jp
- [ ] podio.com
- [ ] atpe.org
- [ ] bluehost.com
- [ ] ebay.co.uk
- [ ] vk.com
- [ ] esurance.com
- [ ] wakeupnow.com
- [ ] citibank.com
- [ ] chicagobooth.edu
- [ ] mcmaster.com
- [ ] netsuite.com
- [ ] freeagent.com
- [ ] www.bankhapoalim.co.il
- [ ] promapp.com.
- [ ] bbvacompass.com
- [ ] strava.com
- [ ] goclio.com
- [ ] any.do
- [ ] ffoz.org
- [ ] thomann.de
- [ ] laposte.net
