### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#125]
We will be using Keen for analytics.  The great thing about Keen is that we can choose exactly what we do or do not want to track.

It's important to consider user privacy when we're choosing which events to track, especially with this sort of extension.

Events I think we should track:
- First install
- Browser open (extension initialization)
- Waltz widget shown
- Waltz widget dismissed (show site user is on)
- Waltz widget clicked (show site user is on.  that might be a privacy issue, though)
- credentials form dismissed
- auth with Cy required (clef wave shown)
- clef wave dismissed without scanning
- logout request from Clef
- edited site in settings
- forgot site in settings
- changed Cy url
- uninstall extension (not sure if we can track this..  probably, though)
- click the browser action
- click the context menu
- tutorial started
- sites page shown
- settings page shown

**Comment by jessepollak** [comment]
We can definitely track uninstall (we should also do a few other things in there).

Question — do we want to associate a UUID with these events or no?

**Comment by josephwegner** [comment]
Right, I meant to ask that.

Personally, I think a UUID is fine.  As long as we don't include any other user information, there's no way to track the UUID back to an actual person.  But, it'd be nice to see "X number of users have dismissed Waltz 500 times.  All of them are running Chrome Canary".

**Comment by josephwegner** [comment]
Well, I guess I got them all :)
- [x] First install
- [x] Browser open (extension initialization)
- [x] Waltz widget shown
- [x] Waltz widget dismissed (show site user is on)
- [x] Waltz widget clicked (show site user is on.  that might be a privacy issue, though)
- [x] credentials form dismissed
- [x] auth with Cy required (clef wave shown)
- [ ] clef wave dismissed without scanning
- [x] logout request from Clef
- [x] edited site in settings
- [x] forgot site in settings
- [x] changed Cy url
- [ ] uninstall extension (not sure if we can track this..  probably, though)
- [ ] click the browser action
- [x] click the context menu
- [x] tutorial started
- [x] sites page shown
- [x] settings page shown

**Comment by jessepollak** [comment]
Is this up on a branch somewhere. I'd like to check it out etc.

**Comment by josephwegner** [comment]
I may not have pushed the branch.  I will when I get home.

**Comment by jessepollak** [comment]
cool thanks
