### ISSUE TITLE
Sharing with Facebook doesn't really work

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#136]
On the sites list after the tutorial, there's this giant "share that feeling with your friends on facebook".

When I click it, I get a facebook popup with an error message saying "An error occurred.  Please try again later."

**Comment by jessepollak** [comment]
This is because of Facebook sandbox mode, thanks for the heads up thought. I'll leave this open till we switch it out of sandbox mode.

**Comment by jessepollak** [comment]
Took it out of Sandbox mode, should work now.
