### ISSUE TITLE
Write sharing messages for FB and Twitter

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#137]
After creating a site through the tutorial, you get the option to share on twitter.  The message you're defaulted to is

"I just setup @getwaltz on Twitter - getting rid of more passwords!".  I don't really think that's a grammatical sentence.

It would probably make more sense to do "I just setup @getwaltz on Twitter - it feels great to be getting rid of passwords!"

**Comment by jessepollak** [comment]
lol, placeholder got shipped!

**Comment by jessepollak** [comment]
We're still writing all the sharing messages.
