### ISSUE TITLE
Add separators to sites/options page

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#140]
It's not a huge issue, but it takes an unnecessary amount of visual work to associate which sitename/username combo matches up with the correct decrypt/forget buttons.

I just tested out putting border-bottom: 1px solid #f3f3f3 on the <li>s, and it looks pretty good.  It's a light enough color that it doesn't draw from the design, but it does give some visual hints to the user.

**Comment by jessepollak** [comment]
Cool, I can get on this.
