### ISSUE TITLE
Initial Tutorial Message

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#141]
Current copy:

> You're 90% of the way to getting rid of your passwords.
> 
> Let's finish that last 10%.

I get the gist, but I'm not sure that the user will.  They're actually pretty much 0% of the way there at this point, because they haven't added any sites :)

This is rough, but what about something like:

> Congratulations!
> You've taken the first step towards getting rid of passwords
> 
> Let's finish the process.

(I'm unsure about the "Congratulations!", but I feel like we need something up there.)

**Comment by jessepollak** [comment]
@brennenbyrne will have thoughts on this, he's running copy control.

**Comment by iamb55** [comment]
I get the change here, and see the problem with the original, but do think that the 90-10 split helps people feel less daunted about a tutorial and setup (they do have to go through a few steps to get Waltz working, including downloading the Clef app). Perhaps something more along the lines of:

"Welcome! 
By installing Waltz, you're almost free of your passwords.
You've already done 90% of the work, but we have a few more steps to get you set up."

**Comment by josephwegner** [comment]
Love that, Brennen.  Let's do it.

—
Joe Wegner
joe@cultivatestudios.com
(630) 297-7563
