### ISSUE TITLE
Grey out Sites I've Already Setup in the Tutorial

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#143]
Right now, the tutorial suggests Twitter, Facebook, and Github.

If I run through the tutorial, setup Github, and then try to run through the tutorial again, Github is still an option.  What's worse, if I click on Github, the tutorial starts on that page.  It fixes itself once I click on the Waltz icon and get logged in, but it shouldn't behave like that either way.

I like how we're greying out and checking sites on the sites list page..  That same effect would be nice in the tutorial, and make sure that when the page gets clicked the tutorial doesn't start.

**Comment by josephwegner** [comment]
When you click on a greyed out site, the tutorial still starts on that page.  I think it even logs you out, which is kinda lame.

Consider this low priority, cause it doesn't delete data and I don't really understand why a user would do this in the first place..  But, a ticket nonetheless.

**Comment by jessepollak** [comment]
Bah yeah.

**Comment by jessepollak** [comment]
Whoops, didn't mean to reclose that.
