### ISSUE TITLE
Waltz Server Base URL doesn't Refresh after Saving

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#146]
It seems like, even after hitting the save button on the settings page, the new Cy URL doesn't work.  You have to restart your browser or refresh the extension to get it to take.

**Comment by jessepollak** [comment]
Ah its probably getting saved but not refreshed in settings. Will fix.

Jesse Pollak
CPO at Clef
jesse@getclef.com

**Comment by jessepollak** [comment]
Super pleased with the solution on this one.
