### ISSUE TITLE
Tutorial Slides are too Tall

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#148]
I think they got taller when we added the new copy to the first slide.  I'm on a 13" MBP, and I can just barely see the next step button.

I can scroll down (though it's not obvious), but the background color on the page doesn't stretch that far so it looks lame.

I would like to say that this isn't a huge issue, but I think that 13" MBPs are pretty common.  They're the poor man's apple :)

**Comment by jessepollak** [comment]
This needs a fix.

**Comment by jessepollak** [comment]
Shrinking the font size a bit should do the trick. I'll get to it.
