### ISSUE TITLE
When logging in on one tab, the waltz widget stays up on other tabs

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#149]
This just happened to me on Github.  I think a lot of sites autorefresh, but we can't count on that.  It becomes a problem if the user clicks the widget on the other tab when they're already logged in - Github gave me an error page.

I believe we have all the tools we need to hide the waltz widget on all tabs with a certain domain.  It shouldn't be hard to hook the login process and executeScript on all the relevant tabs.

**Comment by jessepollak** [comment]
This can be done.

**Comment by jessepollak** [comment]
OK, I just pushed e185527a4c48a6bcacd066c9884275dd229374d1, which refreshes tabs that share the same domain as the tab that is being logged in to.

This isn't perfect, but it's a good solution for now.
