### ISSUE TITLE
Introductions

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#15]
@josephwegner @brennenbyrne @landakram I'd like y'al to meet @apandhi. 

I met him at hackNY and was super impressed and we've been talking over email for the last few weeks. He really likes Clef, and like Joe, has offered to help out with some of the open source stuff we do — including this extension.

I'm really excited to have him!

@apandhi — a brief intro to who we are:

I run product and dev everything technology non-mobile at Clef.

@landakram runs everything mobile is our CTO

@brennenbyrne is the boss; he no longer codes :( but architected our entire original system and is very technical

@josephwegner is an unbelievably awesome person (like you) who's been helping us out on the side with Vault etc

chime in everyone else!

**Comment by jessepollak** [comment]
Also, we have an open chat about all this in this hipchat room: http://www.hipchat.com/gHZ3YHExT

**Comment by iamb55** [comment]
Hey Ashish, it's great to meet you! Thanks for helping out

**Comment by landakram** [comment]
Great to meet you Ashish!

**Comment by jessepollak** [comment]
Another introduction!

Everyone who hasn't already, meet @lolux.

Laurence is probably the coolest person ever. He's been a Clef user since pretty much day 1 and has contributed to our WordPress plugin. He's still learning the codez, but he's learning fast and will be helping out with testing (and contributing soon, I'm sure).

Boom!

**Comment by josephwegner** [comment]
Hey - great to meet you all!  Thanks for helping out - I'm super pumped to get the vault released, and more importantly see Clef take off!

**Comment by apandhi** [comment]
Hey guys! Great to meet you guys also!

I guess I should introduce myself. My name is Ashish. I'm the lead developer at Essence Labs. I recently launched listr.io. Yup that's about it for me.

I'm looking forward to working with you guys!

**Comment by lolux** [comment]
Gentlemen,

It's an honor to meet you. If you're ever passing through Orlando and need
a place to stay or a cold drink, look me up.

This Vault idea is really awesome. Man, I was just getting excited about
Clef payments, and now another killer Clef creation to boot -- boooom!

Speaking of awesome, thanks for the unbelievable intro, @jesse. Honestly, I
can't explain the mysterious reasons why, but being boomed by Jesse is one
of the things that makes life worth living.

I'm probably the most unlikely person to be here from a coding skills
standpoint (or lack thereof!). (I learned HTML in the early days when
dinosaurs roamed the earth and AOL gave you 5MB free personal home page
space to try your hand at HTML hacking!) I can probably be the best help by
testing stuff, giving constructive feedback, brainstorming ideas, that sort
of thing. I've been an avid LastPass user for a while, so I'll likely
be comparing the Vault experience with LP when I give her a kick in the
tires.

(And yes, @jesse, I'm still racking my brain for ways to incorporate the
bumper stickers with Vault marketing. Might have to stick to the six-letter
ones for Vault. I'm stumped on the four-letter version without adding more
words. :-)

peace,
LO
