### ISSUE TITLE
Logged out of Waltz, still logged in to Gmail

### ISSUE THREAD

**Issue by iamb55** [waltzio/waltz#150]
A bunch of time elapsed, I'm not sure of the details, but I'll submit them if I figure anything out.

**Comment by iamb55** [comment]
Waltz wasn't logging me out so I just did this: 

Logged out of Facebook
Logged out of Gmail
Logged into Facebook with Waltz
Logged into Gmail with Waltz
Logged out of Clef
Both Gmail and Facebook refreshed
I was still logged into both 

I am up to date with the most recent Waltz and my configs were just rebuilt

**Comment by jessepollak** [comment]
Closing for now, please reopen and grab me if this reoccurs.
