### ISSUE TITLE
Rethink credential input UX

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#17]
Right now, credential input stinks. We need to change it.

Here's what I'm thinking.
1. You hit a site you haven't added to Vault yet.
2. You click the spinner.
3. You log in to Clef if you haven't already.
4. Everything gets an opacity overlay except for the username field and a message displays something like "Input your username"
5. Same thing for a password.
6. Highlights the input button and tells you to click it to "save your credentials with Vault and log in"
7. Vault saves your credentials and logs you in

thoughts?

**Comment by josephwegner** [comment]
Seems like we've figured this out, mostly
