### ISSUE TITLE
Request (If Possible) to Add Waltz & Clef Compatibility to Tech & News Site, The Verge

### ISSUE THREAD

**Issue by paultran47** [waltzio/waltz#172]
I know very little of coding, but if anyone possibly could, to add Waltz and Clef compatibility to signing into The Verge, or http://www.theverge.com, would be absolutely wonderful! :)

**Comment by josephwegner** [comment]
Hi @TranLePhu,

We'll add TheVerge onto our list of sites to setup in Waltz.  Thanks for the feedback!

**Comment by jessepollak** [comment]
I'm going to close this because we've added it to the list of sites. @landakram started working on this, I know, any progress?

**Comment by josephwegner** [comment]
@landakram @TranLePhu The verge is added!  It will go out in our next release.
