### ISSUE TITLE
Browser Action Page Not Found

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#173]
Ruh roh..  still looking into this one, but in case anyone has better ideas..

![screen shot 2013-12-18 at 3 12 23 pm](https://f.cloud.github.com/assets/657707/1777677/33211b6a-6829-11e3-9c6b-438bc3d5e88d.png)

**Comment by jessepollak** [comment]
This is a weird one.

**Comment by josephwegner** [comment]
I'm an idiot, I had gh-pages checked out.

Can we do some analytics on how many issues I close with "I'm an idiot" in the comment?
