### ISSUE TITLE
Not recognizing logged in state on Amazon.com

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#177]
After logging in to Amazon, the Waltz login button appears at seemingly random times. E.g., just now it appeared after I landed on the third product page while shopping. This has happened to me several times now. It seems like Waltz doesn't recognize that I am already logged on or that Waltz recognizes it for a time and then loses it.

I know that Amazon asks me to re-enter my password before certain actions such as checking out, viewing my account info, etc. What I am talking about here occurs not during these events but during normal browsing products in the store.

**Comment by josephwegner** [comment]
Must be that we're checking the wrong element to see if the user is logged in.. We'll get on that - thanks @lolux

**Comment by jessepollak** [comment]
I would guess that is the case @josephwegner, I can look into this later today.

**Comment by lolux** [comment]
Noob question: if we are nuking the session cookies on logout, then could
we forgot about checking a page element to determine logged in state and
just check whether the same cookie that gets nuked on log out exists as an
indicator of being logged in?

**Comment by jessepollak** [comment]
Unfortunately, the cookies aren't a good indicator for logged in state
because they often exist even if a user isn't logged in :/

**Comment by lolux** [comment]
Did another round of testing today. These three URLs appear to be "random" culprits:

http://www.amazon.com/b/ref=gbsl_tit_l-1_4142_11fef3d0?ie=UTF8&node=7755244011&field-enc-merchantbin=ATVPDKIKX0DER&smid=ATVPDKIKX0DER&pf_rd_m=ATVPDKIKX0DER&pf_rd_t=701&pf_rd_s=left-new-1&pf_rd_r=0BWEJ5DH323C0WV61D03&pf_rd_i=20&pf_rd_p=1671394142

http://www.amazon.com/gp/rate-it/ref=pd_bzer_redirect_c

http://www.amazon.com/gift-cards/b/ref=topnav_giftcert?ie=UTF8&node=2238192011

I tested with this "check": `"check": "a:contains('Sign Out'), a[id='nav-item-signout']",` but it had the same result on these .

This is a very small issue . . . I remain perplexed nevertheless.

**Comment by josephwegner** [comment]
@lolux I am guessing that this is an issue of the `check` element not being loaded on the page by the time that Waltz looks for it.  This is common on javascript based sites, and I know that Amazon's header is a big culprit of stuff like this.

We have some code already in there that checks every 300ms for the first 6 seconds of the page load...  So, even if it loads late, it should disappear (unless it takes > 6 seconds to load).  Are you sure that that is not happening?  It's possible that we either have a bug in that process or something truly unusual is happening.

Unfortunately I'm not able to repro, so I can debug..  If you have any specific steps to recreate the issue, that would be super helpful in helping me find what's going on.

**Comment by lolux** [comment]
Just now, clicking on the middle of the three URLs above causes the issue for me: I'm logged into Waltz and Amazon, but the Waltz button appears on that URL. (A few days ago all three URLs were doing it.)

I'm happy closing this issue for now. . . .

**Comment by josephwegner** [comment]
@jessepollak Were you able to repro this before you fixed it?

Perhaps it's actually unrelated, but I do think  saw on my localhost that the check retries aren't working anymore.  I can create a new issue for that, if that's not what the problem is here.

**Comment by jessepollak** [comment]
Yeah reproduced and fixed. I haven't seen that behavior, can you open a new
issue please.
