### ISSUE TITLE
Create FAQ on getwaltz.com

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#178]
I'm getting a lot of pretty similar questions related to Waltz - I think we should create a FAQ page/section on getwaltz.com

Questions I think should be there:
- What is Waltz doing with my passwords?
- Can I have multiple accounts for one site?
- Why doesn't Waltz work on every site?

**Comment by jessepollak** [comment]
This would be really great to have.

**Comment by jessepollak** [comment]
We have gotten _so_ many support requests with these questions.

**Comment by josephwegner** [comment]
Add to the list:
- Does Waltz change my passwords?
- How do I use Waltz in mobile?

**Comment by josephwegner** [comment]
FAQ created in 99cf2295d48671350a11779be79ae92ab1279561
