### ISSUE TITLE
Cy not getting logout requests

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#179]
I haven't researched the cause of this at all, but I was helping Laurence with a site config, and I wasn't getting logged out of Cy when I logged out of the app.

As a note, I _am_ logged out of Clef..  but my session with Cy is still valid.

**Comment by lolux** [comment]
I'm getting the same . . . I think this started about three hours ago. I was able to log out of Waltz earlier this evening.

**Comment by jessepollak** [comment]
Investingating.

**Comment by jessepollak** [comment]
This looks like something on our end. I just restarted our logout hook service and it seems to be working again. Will dive deeper into what caused the issue tomorrow.

**Comment by lolux** [comment]
Not sure if this is related, but Waltz appears non-functional this morning. The button appears when I visit a Waltz site (e.g., Amazon), but nothing happens when I click the button. Reloading the dev and normal versions didn't fix it. Also, re-opening Chrome didn't either. Hmmm....

**Comment by josephwegner** [comment]
My computer is restoring to a new HD right now, so I'm unable to test.  It
seems that Clef is working on my mobile, so it must be Waltz.  I'll dig in
as soon as I'm able.

**Comment by jessepollak** [comment]
...Waltz's API server crashed, not sure why, just rebooted and all is well.

**Comment by josephwegner** [comment]
Jesse, was it hung or crashed?  If it's a full crash, it should probably
restart itself, right?

**Comment by jessepollak** [comment]
It was fully down. There was no docker container active. When I added an empty commit and pushed it went right back up...

**Comment by jessepollak** [comment]
Also, because of the way dokku seems to work, I can't see any past logs :/

**Comment by josephwegner** [comment]
Ah, that really stinks.  I will do some research around setting something
like LogEntries up.

**Comment by jessepollak** [comment]
Yeah, very strange.

On another note, I just ran a migration that fixed the user session for all the users that would have been messed up by this logout failure.

**Comment by lolux** [comment]
I'm still getting errors while trying to test Waltz for the last 20 min or
so. Can't log in to Waltz. I can scan the wave, but after wave disappears
and the Clef logo appears, nothing happens. When I log out of the Clef app,
nothing happens. It looks like I'm not logging into Waltz.

**Comment by jessepollak** [comment]
Investigating now.

Jesse Pollak
CPO at Clef
jesse@getclef.com

**Comment by jessepollak** [comment]
Hmmm, I'm not seeing that on my end.

**Comment by jessepollak** [comment]
I think this likely has to do with the migration I ran to fix the logout issue.

**Comment by jessepollak** [comment]
Laurence, does the Clef logo disappear when you try to log in?

**Comment by jessepollak** [comment]
Can you check the javascript console to see if there are any errors?

**Comment by lolux** [comment]
Just now I was able to log out of Waltz via the phone app for the first
time in a while. I was getting lots of weird issues. It looks like it's
coming back to normal. Just did a successful log in at Amazon.

**Comment by jessepollak** [comment]
So log in worked for you? What other weird issues were you getting?

**Comment by lolux** [comment]
event.returnValue is deprecated. Please use the standard
event.preventDefault() instead.
jquery-1.8.0.min.js:2chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/third_party/jquery-1.8.0.min.js
Waltz analytics not tracked show_widget
 Object {UUID: 398409660, has_network_connection: true, chrome_version: "5.0
(Macintosh; Intel Mac OS X 10_9_1) AppleWebKit…ML, like Gecko)
Chrome/31.0.1650.63 Safari/537.36", protocol: "https:",host: "www.amazon.com
"…}
 analytics.js:94chrome-extension://nelhcooojhpcgojgkedaoicnjkjkijod/static/js/shared/analytics.js
Resource interpreted as Font but transferred with MIME type text/plain: "
chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Medium.otf
". filing_tools.html:1chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/filing_tools/filing_tools.html
Resource interpreted as Font but transferred with MIME type text/plain: "
chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Bold.otf
". email_sharing.html:1chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/share_tools/email_sharing.html
Resource interpreted as Font but transferred with MIME type text/plain: "
chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/fonts/GothamSSm-Book.otf
". global_tools.html:1chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content/global_tools/global_tools.html
1. Blocked a frame with origin "https://api.waltz.io" from accessing a
   frame with origin "https://www.amazon.com". Protocols, domains, and
   ports must match.
   inject.js:202chrome-extension://jciblakmllnhbhjjgkbkeihelcndmgnh/inject/inject.js
2. Blocked a frame with origin "https://clef.io" from accessing a frame
   with origin "https://api.waltz.io". Protocols, domains, and ports must
   match. inject.js:202chrome-extension://jciblakmllnhbhjjgkbkeihelcndmgnh/inject/inject.js
   2.

This is what appears in console when I'm on the amazon login page pre-Waltz
login . . . not sure if this reveals anything useful.

The weird stuff earlier was that (a) I couldn't log out of Waltz even
though I was logged out of the phone app and (b) I couldn't log in to any
sites even though the wave would scan and the Clef logo would appear
briefly as during a normal login.

**Comment by jessepollak** [comment]
Yeah I fixed the logout issue. The login one perplexes me. Those frame
blocking warnings scare me. Investigating.

Jesse Pollak
CPO at Clef
jesse@getclef.com

**Comment by jessepollak** [comment]
Laurence, what chrome extensions do you have active?

**Comment by jessepollak** [comment]
Could you open up the javascript console, then go to "Sources," then click Content scripts in the top left, then find the one with the ID jciblakmllnhbhjjgkbkeihelcndmgnh and look what files are inside?

https://www.dropbox.com/s/uz84c9ald1zwq1w/Screenshot%202013-12-21%2014.54.54.png

**Comment by jessepollak** [comment]
Alternatively, just go look here: chrome://extensions/ for the chrome extension with that ID.

**Comment by jessepollak** [comment]
So, those blocked warnings are coming from the Zotero plugin, which is trying to detect whether the frames are top level or not. I installed the extension and am not getting the same warning, because it's wrapped in a try catch, so I'm not sure what's going on with @lolux's version. Not concerned about it.

**Comment by jessepollak** [comment]
The login stuff I am more concerned about, will continue investingating.

**Comment by josephwegner** [comment]
@jessepollak Any updates here?  Can we close, or open a new ticket for the actual issue?

**Comment by jessepollak** [comment]
Let's close for now. I think I fixed the issue on Clef's end and resolved the bugs with @lolux (at least one of them was just a miscommunication). If this pops up again, let's reopen.
