### ISSUE TITLE
Don't save credentials if they are wrong

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#18]
Sometimes you make a mistake when you're entering your credentials. That stinks!

We should detect when this happens and do two things:

1) not save the credentials
2) place you right back into the flow (with the option to dismiss it)

**Comment by landakram** [comment]
I merged something for this in https://github.com/waltzio/waltz/pull/65

I still save the credentials, but re-present the modal if the login fails with an error message (using the check config to see if login was successful).

I didn't spend a lot of time styling the alert message.
