### ISSUE TITLE
Fix 2-factor auth for Github

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#182]

**Comment by lolux** [comment]
Oh, I see you already know about this. I was just going to add an issue for it:
https://www.dropbox.com/s/bpeqpxll4i26o24/Screenshot%202013-12-21%2015.12.44.jpg

This one is weird since it seems to me that the .json has the correct settings already. . . .

**Comment by jessepollak** [comment]
Will fix.

**Comment by lolux** [comment]
Also, help.github.com doesn't include the same sign out check, so Waltz login button appears even though I'm logged in.

**Comment by jessepollak** [comment]
I'm not seeing this broken on my end. Can you check what the name of the input field when you put in your 2-factor token?

**Comment by lolux** [comment]
Here's how I get the error:
1. Log in via Waltz button
2. Enter **incorrect** 2-factor code
3. Waltz returns the error page noted earlier (see screenshot)

I just double-checked, the 2-factor input field is named `otp`, which is what is in the .json.

**Comment by jessepollak** [comment]
OH, so the first time, it works as expected? That makes sense, I guess.

**Comment by lolux** [comment]
Not sure what you mean.

I'm saying that Waltz won't let Github display its error page for failed 2-factor attempts.

Will adding a `nextURLs` param for the 2-factor URL fix this? (Testing. . . )

**Comment by jessepollak** [comment]
I was thinking it was just broken all the time, not just on error. Will
investigate.

**Comment by lolux** [comment]
Not entirely sure whether this is the cause, but I noticed that the
MFA form submits to a different URL than the one set in the `formURL`
param: https://github.com/sessions/two_factor.

Do we need a new `formURL` param in the `twoFactor` object to allow
these sorts of MFA forms to submit properly?

**Comment by lolux** [comment]
Actually, looking at it further, I think this is the same issue as #174 ...

**Comment by jessepollak** [comment]
Yeah, I think it's the same issue.

**Comment by jessepollak** [comment]
Closing this, leaving #174 open.
