### ISSUE TITLE
Fix logout when browser is quit

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#19]
User should be logged out when they open it.

This isn't the best solution security wise and I'd like to think more on how we could improve this.

**Comment by josephwegner** [comment]
You mean they should be logged out whenever they first open their browser?  So we're killing the "remember me" things?  That seems dangerous.

**Comment by jessepollak** [comment]
No, I mean we should check whether they are still logged into Cy and if not log them out.

**Comment by jessepollak** [comment]
This is broken right now because I keep a logged_in variable and check whether that's true before I do authenticationChecks. This variable should be switched to storage so it persists beyond shutdown.

**Comment by jessepollak** [comment]
Fixed in #62
