### ISSUE TITLE
Can't Change Cy URL

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#197]
I went in to try and work on some Cy tickets, and found that I can no longer change the Cy URL...

I _think_ there is a race condition when `setOption` calls `getOptions`...  `getOptions` calls `setOptions` internally before passing the retrieved options back to the `setOption` callback..  I think there's a race to see if the `setOption` callback or the `setOptions` call finishes first.  I'm not sure why `getOptions` is calling `setOptions`, but it looks like a weird fix that probably has some reasoning that I don't understand.

Here's the [offending code]:(https://github.com/waltzio/waltz/blob/develop/static/js/shared/storage.js#L157)

```
Storage.prototype.getOptions = function(cb) {
    var _this = this,
        promise = $.Deferred();

    this.get(this.OPTIONS_KEY, function(options) {
        var ret;

        _.defaults(options[_this.OPTIONS_KEY], _this.optionsDefaults);
        ret = options[_this.OPTIONS_KEY];
        _this.setOptions(ret);

        if (typeof cb === "function") cb(ret);
        promise.resolve(ret)
    });

    return promise;
}
```

@jessepollak Can I nuke that `setOptions` call, or is there a good reason for it?  If I'm understanding things correctly, calling `setOptions` should just set the options back to whatever they already are..  Unless it's for defaults.

**Comment by jessepollak** [comment]
I honestly have no idea why that setOptions is in there, but there may well be a good reason. I'm not sure if you've noticed, but we've done some _crazy_ things with the Storage class. We were hitting problems with the fact that it wasn't thread safe, so now we proxy _all_ sets and gets through one instance of StorageBase.

@landakram do you have any comments on this?

**Comment by josephwegner** [comment]
Good 'ol git blame..

Looks like it was @landakram, and had something to do with lodash.

https://github.com/waltzio/waltz/commit/13bed624c583b5cd404a70ed8fcf92194fe0a805

I have noticed that the storage class is getting a bit crazy.  Kinda fun that there's like 4 different ways to set something in storage :)

**Comment by jessepollak** [comment]
Yeah...it's very crazy.

**Comment by jessepollak** [comment]
So, the fix I just pushed _definitely_ fixes this bug. The problem was that we for some reason for go to switch out that chrome.storage.local.set with our model's version of that (that proxies it to the background page and does a bunch of other things).

That said, I'm still a little confused why we have the storage.setOptions in the storage.getOptions, @landakram can you illuminate?
