### ISSUE TITLE
What do we call this thing?

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#2]
Currently called "Vault", which is fine..  But not exciting.

I suck at naming, but here are the things I think:
## Following the musical theme, of "clef"
- Accolade ("Connects two or more lines of music that are played simultaneously.")
- Tablature ("For guitars and other plucked instruments it is possible to notate tablature in place of ordinary notes")

**As I said, I suck at naming, so I don't actually have any other ideas right now.  I'll update this later**

**Comment by jessepollak** [comment]
I'm into the music them. I'll keep thinking about it.

**Comment by jessepollak** [comment]
bypass.io

**Comment by josephwegner** [comment]
Does this getting closed mean you bought it?!?!

**Comment by jessepollak** [comment]
I just went to buy it...and it's not available. fack.

**Comment by josephwegner** [comment]
NOOOOOOO.. Back to the drawing board.

**Comment by josephwegner** [comment]
It looks like into.io is available.  Not a great name, but it's definitely applicable!

**Comment by josephwegner** [comment]
Nevermind..  Even domainr's partners are lying to me now.

**Comment by josephwegner** [comment]
overpass.io
underpass.io
clasp.io

**Comment by jessepollak** [comment]
Brennen says squid.io/getsquid.com

**Comment by jessepollak** [comment]
I like clasp, but it's kind of hard to say.

**Comment by jessepollak** [comment]
Brennen and Mark are in favor of squid, I don't like it much but could settle. I liked into, but it's hard to say and parse when you're having a conversation about what you're using. Clasp is too hard to say.

**Comment by josephwegner** [comment]
I still don't like squid, but I'm with you that I could definitely settle.  I just want the thing launched!

I agree, into is hard to talk about.  It's a nice idea, but impractical.  Same thing in clasp.

I can do squid if we just want to decide and be done with it.

**Comment by jessepollak** [comment]
We'll keep thinking about this, but if we don't have something better by Monday, we'll go with squid.

**Comment by apandhi** [comment]
Well if you want to follow music themed, here is a list of possible choices:
http://www.classicalworks.com/html/glossary.html

I like forte.io

**Comment by jessepollak** [comment]
Ah, we all loved forte, but it's not available :(

**Comment by jessepollak** [comment]
The latest contender is waltz. We can buy waltz.io and getwaltz.com.

It's a little tricky to say, but I like it.

**Comment by apandhi** [comment]
I really like waltz. Move from site to site as if you were dancing a waltz (or something like that. I'm not a marketing person!)

**Comment by jessepollak** [comment]
Also, it's like a dance between Clef and passwords :)

**Comment by josephwegner** [comment]
:+1:  for waltz.  I say buy it.

**Comment by jessepollak** [comment]
OK, I'm going with Waltz.

**Comment by jessepollak** [comment]
Bought.
