### ISSUE TITLE
ignore URLs in site configs

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#202]
.json enhancement suggestion: add new parameter that allows us to exclude/ignore specific URLs and/or URL patterns.

Why needed? This has come up several times in testing. E.g., blog.prezi.com displays the Waltz button even though it is not a site meant for Prezi users to log in. Currently, there is no way to exclude this URL from the pattern match without forcing a too restrictive pattern (i.e., one that only works for one subdomain).

**Comment by josephwegner** [comment]
@lolux I have added a new key to the site configs called `match`.  This should be a regular expression that will match all pages that the Waltz button should show up on.

For your case of excluding specific subdomains, you need to use a [negative lookahead](http://www.regular-expressions.info/lookaround.html) to check for the offending subdomain.  Here's an example you can use - it should be pretty straightforward to figure out which pieces need to change with each site.  Lemme know if you have trouble, though.

```
 "match": "https?://(?!blog\\.)([^.]+\\.)?example\\.com/" //Excludes blog.example.com
```

**Comment by lolux** [comment]
Thanks for adding this!

I had to make one change to get it to work on prezi.com: deleting the last forward slash. So, it works like this for me:

`"match": "https?://(?!blog\\.)(?!beautifulbits\\.)([^.]+\\.)?prezi\\.com",`
