### ISSUE TITLE
Add build task for minifying extension files and removing unecessary ones

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#21]
Grunt, FTW.

**Comment by josephwegner** [comment]
I added a compress action to grunt this morning (and stupidly pushed it to the new-credential-input branch...).  Right now it compresses everything in the extension dir to ../waltz.zip

**Comment by jessepollak** [comment]
OK, there's also a grunt plugin for building chrome extensions, which we could look into.

**Comment by josephwegner** [comment]
Let's do that.  I (or someone ) can pull the changes I made out of new-credential-input, and do the correct work on master.  That way we do the _right_ thing, and I don't look like an idiot for committing on the wrong branch!
