### ISSUE TITLE
Add Analytics to Website

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#213]
I'm thinking that it might be fun to have some sort of analytics on the website...  Not in any great detailed sense, but just something to give an indication that people are _actually_ replacing their passwords with Waltz/Clef.

I'm thinking something like

"1,542 people have skipped passwords this week"

Or, at least something similar.  I'm open to ideas.

Anyone have any objections to having this on the website?  I know it'll publicize it if Waltz is doing bad, but it's probably better to not plan on that :)

**Comment by lolux** [comment]
:+1:

**Comment by jessepollak** [comment]
I like the idea of this.
