### ISSUE TITLE
Validation for empty credentials fails on auto-fill

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#216]
https://www.dropbox.com/s/bwv1marqqexhgko/Screenshot%202013-12-27%2015.47.11.png

For some reason, val() doesn't pick up on auto-filled values. This is an issue with [these lines](https://github.com/waltzio/waltz/blob/develop/static/js/client/waltz.js#L589).

**Comment by josephwegner** [comment]
what? That's super weird..  I'll look at it.
