### ISSUE TITLE
Install Event Called Too Often?

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#224]
I can't say for sure what's going on, but it seems like the install event is being called _way_ more often than it actually should be.  Keen is showing an increasing number of install, with 306 on Friday increased to 443 on Sunday.  Similar events like activated and first_tutorial are only showing ~20 hits per day.

Possible causes:
- Race condition on when the `install` event is called
- `install` is called when the extension gets updated
- We are having an _incredible_ amount of immediate churn
- Tutorial is not necessarily running on first install.  Perhaps activation also isn't running, which would explain why we're not seeing an increase in `show_widget` events.

**Comment by lolux** [comment]
Is it possible that the install the event is called when I press reload to
test site configs? I have prob reloaded a couple hundred times at least...

**Comment by josephwegner** [comment]
It's very possible.  I meant to mention that.  Do you have develop mode set on your localhost?  All of the Keen code should be stubbed when you're in develop mode.

**Comment by jessepollak** [comment]
Checking in from a far land: install is called on updates, my bad.

**Comment by josephwegner** [comment]
no worries.  It's not necessarily _bad_ that we're tracking upgrades.. Probably just more useful if we can have that under another event.  I'll see if I can get to this this week.

**Comment by jessepollak** [comment]
This is fixed in #262.
