### ISSUE TITLE
Accommodate CSP rules

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#241]
The following test config for LastPass.com yields Content Security Policy ([CSP](http://developer.chrome.com/extensions/contentSecurityPolicy.html)) errors [in the console](https://www.dropbox.com/s/036r6ontidvxasn/Screenshot%202014-01-05%2011.59.36.jpg):

```
{
    "https://lastpass.com/*": {
        "name": "LastPass",
        "logout": {
            "cookies": ["PHPSESSID"]
        },
        "login": {
            "urls": [
                "https://lastpass.com/index.php",
                "https://lastpass.com/"
            ],
            "formURL": "https://lastpass.com/login.php?",
            "method": "POST",
            "usernameField": "email",
            "passwordField": "password",
            "hasHiddenInputs": true,
            "check": "div#actions"
        }
    }
}
```

Do CSP's such as LastPass's preclude Waltz integration altogether?

**Comment by jessepollak** [comment]
Added code to prevent these warnings. Closing.
