### ISSUE TITLE
Assess z-index configuration for all Waltz iframes/overlays

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#254]
Previously, we've discussed this issue with regard to the Waltz button being hidden behind header elements on some sitse (e.g., https://github.com/waltzio/waltz/pull/199#issuecomment-31230955; Brennen mentioned another, but I can't find the issue ref. at the moment; I've come across a couple more examples that I haven't reported).

Here is a new case where the problem applies not only to the button but also to the login form:
https://www.dropbox.com/s/aj40dp43l6hld10/Screenshot%202014-01-09%2012.09.53.jpg (from http://thomists.wordpress.com/).

Since we're starting to see overlay issues with some frequency, I think its time to address them. Is fixing these overlays as easy as going for bigger z-index numbers?

**Comment by lolux** [comment]
Possible way to find highest z-index:

```
function getMaxZIndex() {
    var zIndexMax = 0;
    $('div').each(function () {
        var z = parseInt($(this).css('z-index'));
        if (z > zIndexMax) zIndexMax = z;
    });
    return zIndexMax;
}
```

(Source: [SO](http://stackoverflow.com/questions/8450382/getting-highest-z-index-value-using-jquery-live-to-ensure-all-elements-considere))

Another possibility: use [max 32-bit integer](http://stackoverflow.com/questions/491052/mininum-and-maximum-value-of-z-index)—2147483647—for the login button and password input overlays.

**Comment by jessepollak** [comment]
Yeah, we have serious z-index problems. The problem is, we have overlapping
things that need high z-indexes (credentials overlay, clef overlay,
tutorial prompts, login button).

What we really need to do is make all of our z-indexes into SASS variables
and make them extra high.

Is there a max z-limit? For some reason I always thought it was 9999.
