### ISSUE TITLE
Solve Pandora's box

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#265]
Following up on https://github.com/waltzio/waltz/commit/a5d6aad8f2f8d69b3b86101c1a39b5da14ff2b71#commitcomment-5037954, thanks for the much helpful tips. I'm trying to apply them to other cases. First up, Pandora, which seems to be a true Pandora's box for Waltz:
- From all I can tell looking at the Network tab, Pandora's form uses GET instead of POST. I think the formURL is as follows, but I'm not certain.
- Also, the cookies seem to have the same ninja powers as Wikipedia's: manually deleting all the cookies under .pandora.com in console does not log user out.
- The check element is playing dirty: all logged in elements that ordinarily work as check elements appear in the page's source regardless of log in state. I think ajax determines which ones to show. So, I can't find an element to serve as a check.

```
{
    "*://*.pandora.com/*": {
        "name": "Pandora",
        "logout": {
            "cookies": ["at", "atn", "v2regbstage"]
        },
        "login": {
            "urls": [ ],
            "formURL": "https://www.pandora.com/radio/jsonp/v35",
            "method": "GET",
            "usernameField": "email",
            "passwordField": "password",
            "check": ""
        }
    }
}
```

**Comment by josephwegner** [comment]
Without actually looking at the problem...

You might be able to use a :visible psuedo-selector for the check.  Then it
will only match the check elements if they're visible.

**Comment by lolux** [comment]
Hmmm, no joy on attempts to apply :visible pseudo-selector on `a` element from this line: `<a class="signoutMenuItem" href="#" address="true">Sign out</a>`

**Comment by jessepollak** [comment]
Pandora is hard...

**Comment by jessepollak** [comment]
Fixed by new Waltz.

**Comment by lolux** [comment]
:bow:
:boom:
