### ISSUE TITLE
html/sites.html not displaying

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#267]
Is this just me, or can anyone else confirm:
1. select Waltz extension button
2. select "Site where I can use Waltz already"
3. Blank page for html/sites.html

Chrome version 31.0.1650.63. Waltz version 1.0.8.2 (not my dev version but the live version from Chrome store).

**Comment by jessepollak** [comment]
Can you check your background page?

**Comment by landakram** [comment]
I noticed that I couldn't see sites.html either, but I was on the dev version. I also noticed that Waltz did not display on sites. 

I trashed the dev version and downloaded the live version and everything displayed fine. 

I'm pretty sure I've seen the same sort of behaviour before (happened after an update), but I could have sworn I had the dev version that time too. Either way, it has something to do with updates.

**Comment by lolux** [comment]
I could have swore that I rebooted after disabling dev version and enabling live version. But apparently another re-boot did the trick for me: https://www.dropbox.com/s/khptajv6tipuwkc/Screenshot%202014-01-14%2014.00.49.jpg.

Sorry for the bother...
