### ISSUE TITLE
Passwords in settings screen can be decrypted or changed without authing with Clef

### ISSUE THREAD

**Issue by bradp** [waltzio/waltz#275]
![screen shot 2014-01-20 at 5 20 28 pm](https://f.cloud.github.com/assets/66798/1959554/f231fa84-8231-11e3-93f6-fcc6837252a1.png)

**Comment by jessepollak** [comment]
If you're already logged in, that's intended behavior. If you're not, it's most certainly not. Let me know.

**Comment by bradp** [comment]
This happens to me after logging out with clef. And even after deauthorizing Waltz from my Clef account.

In fact, I can log into all sites I have passwords saved for in Waltz at this point, even though its been deauthorized and removed.

:(

**Comment by bradp** [comment]
Alright, I tried this on a new chrome install, setting it up again, and it behaved as expected.

Not sure what went wrong here, but I can't reproduce it.

**Comment by jessepollak** [comment]
This is likely an issue with Waltz getting out of sync with Clef. It's [happened before](https://github.com/waltzio/waltz/issues/179), but I was pretty confident that we'd resolved the issue. I'll look into it on our end again and see if I can find anything. Please keep me informed if it happens again.
