### ISSUE TITLE
Design logo and style guidelines for Waltz

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#29]
Would love to hear people's thoughts about what the "feel" of Waltz should be.

A few different ideas:
- we could go playful and musically, like a white with purple (or another easier color), with serifed fonts
- we could go for the tuxedo vibe

**Comment by josephwegner** [comment]
I think it should match the vibe of Clef - so somewhat modern.  The clef
logo is the primary thing the user will see, so it makes sense to build the
brand around that.

**Comment by jessepollak** [comment]
we had our first go.

![waltz](https://f.cloud.github.com/assets/1097953/1321306/04fecc36-33af-11e3-82a8-4e19e1d04fa0.png)

**Comment by jessepollak** [comment]
second go.

![w](https://f.cloud.github.com/assets/1097953/1321335/3af8b290-33b2-11e3-8ef8-5ad8c2b11c09.png)

**Comment by jessepollak** [comment]
messing around with a home page

![waltz](https://f.cloud.github.com/assets/1097953/1321497/601db92e-33cd-11e3-91ec-03817f163c2f.png)

**Comment by jessepollak** [comment]
obviously, placeholder icons etc

**Comment by josephwegner** [comment]
I'd like to have some section that says Waltz is using Cy for encryption.  I think Cy is a really cool thing - it's better than how most password managers are doing things.

**Comment by josephwegner** [comment]
Other than that, it's really great.  The logo is awesome.  I freaking love the bow tie.

**Comment by jessepollak** [comment]
OK, we'll keep moving ahead with this pattern then.

In terms of Cy, I think that we should feature it as "encrypted locally" — I'm not 100% sure that we're doing is better than a master key encryption like 1password etc, but I think it is really good that it's all stored locally.

**Comment by josephwegner** [comment]
I suppose that it's not necessarily better than a master key system _yet_.  If Clef ever gets the update to provide some salt, I think this is much better than master key encryption.  Once we get there, stealing the DB has absolutely no value - the critical data only exists on user's local HDs (and then, it is still encrypted).

Anyways, yeah, I don't think the homepage needs to go into great detail about it, but I do want to highlight the fact that no server has access to credentials.  Whether that specifically mentions Cy or not (preferably at least a link) is up to you.
