### ISSUE TITLE
Paypal login broken

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#290]
![screenshot from 2014-02-12 23_07_17](https://f.cloud.github.com/assets/1097953/2163189/d5d40c3a-94db-11e3-959f-8927ddaddc29.png)

**Comment by lolux** [comment]
Looks like some things changed with the "new" homepage design. I'm testing right now. From testing it seems that the second listener is no longer necessary. Working on a fix right now. . . .

I haven't figured out yet what [this new red thing](https://www.dropbox.com/s/lnzkwawecfhhfgu/Screenshot%202014-02-13%2014.20.47.jpg) is.

**Comment by jessepollak** [comment]
Ha, that looks like it's the "x" blown up. I can restyle it when you get
this fixed :)
