### ISSUE TITLE
Login Process

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#3]
Keep security in mind as you review this process:
1. User goes to page with login form
2. User is prompted to login with Clef
3. User clicks login with Clef
4. If user is not already authenticated with clef, authentication overlay is shown
5. User scans the "wave"
6. Extension receives notification that user is authenticated
7. Extension contacts augmenter server with OAuth credentials, and asks for domain-specific unique key
8. Extension decrypts username & password using the key from the augmentor (AES-256 via js-crypto)
9. Extension fills username/password fields on page
10. Extension submits form

**Comment by josephwegner** [comment]
- I will need to read more on how step #6 works - there may be additional steps in there that I'm not aware of.
- We also may need to contact the Clef servers for #7 and #8, if we decided to use the Clef ID as additional salt.  Though, I'm not sure there is any point in that if we are storing salt on the augmenter.
- At MySocialCloud we gave users the option to "Auto Login" or "Auto Fill".  Apparently sometimes people don't want to login right away.  I don't really understand that interaction, so I lean towards just auto submitting the form, but it's something to keep in mind.

**Comment by jessepollak** [comment]
So, the one thing that we need to keep in mind is that to authenticate with Clef, we need to do a server side OAuth handshake with the Clef servers. RIght now, this works like:
1. When the user clicks the Login with Clef button, the wave is loaded in an iframe, which opens up a websockets connection with the Clef servers
2. When the user scans the Clef Wave and the Clef servers verify the user's identity, they push to the wave iframe, which redirects to the redirectURL specified by the application integrating with Clef
3. At that redirectURL, the application that is integrating with Clef receives the OAuth Code, exchanges it for an OAuth Token, exchanges that OAuth Token for user information, then uses that information to look up/create a user and log them in.

For this reason, I don't think that the extension itself can do the actual login process (it needs some sort of backend). So, I think that when the user logs in, they are really logging into the Augmentor. Once they log in to the Augmentor, they can access/create the encryption keys for each domain until they log out of Clef at which point the Clef servers do a logout hook with the Augmentor servers, which deactivates that user session.

Does that makes sense?

**Comment by josephwegner** [comment]
Gotcha - I see how that works.  So the augmentor will just function as an app that supports Clef.  Sounds good to me.

**Comment by jessepollak** [comment]
Exactly.

**Comment by josephwegner** [comment]
The technical pieces of this are done, so I'm closing this issue.  UX isn't finalized, but that's out of scope here.
