### ISSUE TITLE
On WordPress.com credentials input, asks for Wells Fargo username

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#314]
![image](https://cloud.githubusercontent.com/assets/1097953/2553764/1c263764-b6a9-11e3-9654-be607e092f53.jpeg)

**Comment by lolux** [comment]
I couldn't repro on production version: https://www.dropbox.com/s/8sysgtygv43p56g/Screenshot%202014-03-28%2016.58.19.jpg

Or dev version: https://www.dropbox.com/s/32vupvg3j4itfd2/Screenshot%202014-03-28%2017.01.17.jpg

Running Chrome 33.0.1750.152

**Comment by jessepollak** [comment]
I've seen this before for sure, but have done some searching and haven't
been able to replicate either.
