### ISSUE TITLE
Slack would be awesome

### ISSUE THREAD

**Issue by jasonwhat** [waltzio/waltz#316]
Slack is a great tool for team communication (similar to Hipchat) and I think a lot of digital teams are using it. http://slack.com

Thanks for making waltz so awesome.

**Comment by ninjapanzer** [comment]
Slack is a little harder. The login process takes you to <team>.slack.com for the actual login. From my observation of the configurations and documentation thus far the `urls` section doesn't appear to accept wildcards. I plan to look into this a little bit.

**Comment by jessepollak** [comment]
Yeah, this isn't something Waltz currently supports, but it's definitely something it _can_ support.

I think it _may_ actually work to have a config with `formOnly` enabled, no `formURL` or `urls` field and the domain set to `*://*.slack.com`. There may be some errors there from undefined, but logically  I think that would work. Obviously, it would mean that the user would have to visit the login page for their team before they could use Waltz, but it's better than nothing.

Thoughts?

**Comment by ninjapanzer** [comment]
I was reading the sample in #319 so I am going to play with it and see if it would make sense to allow urls to be `patterns` or `strings`

**Comment by jessepollak** [comment]
I'm not sure whether you need the double config object like @lolux has there, but play around with it and let me know. Would be really excited to see a PR with better support for subdomain based login. We have a lot of sites, which we haven't been able to add because we lack support for that.

**Comment by landakram** [comment]
I just checked in on this - with the latest update, you can use Waltz to log in to slack.com w/o a site config. We could make the interaction better (for instance, you have to enter in your email address first to get to the `*://*.slack.com` subdomain for your team and then click the Waltz button there), but I'm going to close this for now.
