### ISSUE TITLE
Support Feedly login

### ISSUE THREAD

**Issue by benjaminzanatta** [waltzio/waltz#320]
It could be nice to be able to login to http://feedly.com/ with Waltz !
Thanks

**Comment by lolux** [comment]
Hi @benjaminzanatta , thanks for the recommendation for adding Feedly. Unfortunately, feedly mandates social login (i.e., https://www.dropbox.com/s/ycfw75mc1au59iu/Screenshot%202014-04-15%2014.51.54.jpg), so Waltz cannot hook into Feedly's authentication process directly.

However, for an indirect Waltz-to-Feedly experience, if you use Waltz to sign into your Google account, then you can use Google to sign into Feedly.

**Comment by jessepollak** [comment]
Accordingly, I'm going to close this issue.
