### ISSUE TITLE
Accommodate Pinterest . . . CSRF

### ISSUE THREAD

**Issue by lolux** [waltzio/waltz#330]
https://github.com/lolux/waltz/blob/site-pinterest/site_configs/pinterest.json
https://github.com/lolux/waltz/blob/site-pinterest/static/img/site_images/pinterest.png

Log out works.
Log in fails Pinterest's CSRF check and redirects here:
http://www.pinterest.com/csrf_error/

Is it even possible to accommodate such checks in Waltz (cf. https://github.com/waltzio/waltz/issues/34#issuecomment-26311296)?

**Comment by jessepollak** [comment]
Bleh Pinterest. Yeah, this login isn't possible with Waltz's current capabilities. Need to fix.

**Comment by jessepollak** [comment]
Fixed by new Waltz.
