### ISSUE TITLE
wikinvest login query params

### ISSUE THREAD

**Issue by ninjapanzer** [waltzio/waltz#336]
Regarding https://github.com/ninjapanzer/waltz/blob/pks/wiki_invest/site_configs/wikinvest.json

The formURL on this page requires a query parameter so as a test I provided the one that the site gives me for testing.

It appears that the query params are stripped when the formURL is requested

**Comment by jessepollak** [comment]
With the new Waltz, Wikinvest should be working. Can you reopen if it's not?

Thanks!
