### ISSUE TITLE
Heuristic vs. Defined 

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#34]
So, I'm starting to think that we should do away with the heuristic login field finder and just do defined configurations for each site, which are super easy to add.

A big question for this:

Should we even worry about the specific form fields or should we just look for the input names and POST route. This would mean that we could log a user in from _any_ page on the domain, but I'm not sure if it would work.

**Comment by josephwegner** [comment]
So, I'm open to being convinced that the heuristic approach is incorrect, but I'd like to hear the arguments.  Is there something that is not working about the current approach that likely cannot be solved with some tuning of the algorithm?

I'm mostly worried that going the defined route will provide a lesser experience for users.  There is no way we can expect to define configurations for anywhere close to the majority of the sites that our users will log into.  And even if we could over time, every additional configuration will require an extension update - that's not hard, but requires me (as the extension owner) to constantly be building and uploading  new sites.

The whole idea behind the extension is that Clef currently has a dangerously small footprint of sites that support it.  What's the point, if we're only marginally increasing that footprint?

(As I said, I'm open to argument, I just want to know why.  I'm often wrong, but I don't like to be wrong "just cause")

**Comment by ahrussell** [comment]
Why not both?  The latter sounds like a better option provided it works -
if it doesn't, we fall back to the old way.

**Comment by apandhi** [comment]
Hm here is an interesting thought. Why not crowd source the sites?

When the extension is loaded, have it pull in a list of all sites and configurations. Let the user be able to say "This is the username box", "This is the login button", etc. After around 10-15 people make the same configuration, you can assume that the configuration is correct and save it to the main document.

This way, you could have clean defined sites that are crowd sourced.

**Comment by josephwegner** [comment]
@apandhi I had suggested this in hipchat at one point, and I actually believe that is the best option.  However, we would have to build the system for receiving and serving that data.

I think it is well worth building that system, but I'm not sure if we should do it for v1.  I'm inclined to get an MVP out ASAP, and tack on the features as we get feedback and have time.

@zrathustra I also think that's probably a good idea.  We still have the issue that we have to build and release a new version every time we have new configurations, but using a hybrid approach will slow down the necessity to release as often and as quick.

**Comment by lolux** [comment]
It might be worth considering allowing users the ability to manually
copy-n-paste credentials too in sites that, for whatever reason, do not
allow either heuristic or defined auto-filling.

For instance, I ran across this situation in using LP with the old version
of Pandora.com, which used Flash-based login forms [insert angry spit here]
and hence required manual copy-n-pasting of my credentials.

(Though maybe JS has improved since then to handle auto filling of flash
form fields too.)

**Comment by josephwegner** [comment]
Yeah, we'll have to figure out a good way to do that.  Currently you can access your usernames/passwords from the options page and copy+paste from there, but that's not a great interaction.  Perhaps we can add another charm to the widget for copy and pasting.

**Comment by jessepollak** [comment]
I think that our discussion in #39 pushes this more towards defined rather than Heuristic. 

We really want this to feel like magic, rather than a password manager. I think this means a few things:
- log in from anywhere
  - if you're on a domain that you can log into, you should be able to log in with one click of the spinner. you shouldn't have to navigate to the login page then click the logo and watch the credentials fill in. fuck that! we'll log in where we want to.
- logout
  - when I click the logout button, I want to be out out out of all my sites. it's just the best feeling in the world. we can't do this unless we've specifically set it up per site (unless we just say fuck all the cookies). 
- registration
  - if I hit a site that I'm not signed up for, but it's supported by Waltz, I should know it! and if I click that beautiful spinning circle, I should have an account registered for me and be logged in. boom, magic.
- shut the ***\* up if i'm logged in or there's no login page
  - I don't want to see that spinning blue circle (even though I love it) if I can't do anything with it. we only want it enabled on places where with one click my life will be improved drastically for the better.

All of these things require fine-tuned site-specific data.

We also want to turn our users into more active users and evangelizers. If we create an awesome tool that people love AND we need their (easy) help, then I think we'll be able to convert users to "contributors" by allowing them to easily figure out what they need to do to add new sites. This is empowering.

That's the core of my argument, though I think @brennenbyrne may have more to say...

**Comment by apandhi** [comment]
If we're doing Defined, then POSTing the data will be no problem. We can create quick templates and store it to a database or a cached file. I suggest we don't keep the main codebase in the chrome extension, though. The update cycles are tedious and it takes about 24 hours for 90% of your users to even get the update (also, this causes issues when moving cross browsers). 

I much prefer the defined method. The log in automatically when you go to the domain or site would be really nice. I really want to create a little clef widget in the chrome toolbar thingy that's a clef icon. You sit down, click that, scan the clef wave, you're good to go. (maybe cross device sessions?)

**Comment by jessepollak** [comment]
OK, in terms of the whole POST question. 

Yes, it can be tricky to recreate a login request. HOWEVER, we have one really awesome thing working for us. No user is logged in when we're logging in. For all Facebook (or any other site) knows, we could be any old user doing any old thing. And, because there's no authentication session, you can't do protections against CSRF (like CSRF tokens).

For instance, let's take a look at Facebook's login form:

```
<form id="login_form" action="https://www.facebook.com/login.php?login_attempt=1" method="post" onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)">
    <input type="hidden" name="lsd" value="AVq6TF4w" autocomplete="off">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td class="html7magic">
                    <label for="email">Email or Phone</label>
                </td>
                <td class="html7magic">
                    <label for="pass">Password</label>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" class="inputtext" name="email" id="email" value="" tabindex="1">
                </td>
                <td>
                    <input type="password" class="inputtext" name="pass" id="pass" tabindex="2">
                </td>
                <td>
                    <label class="uiButton uiButtonConfirm" id="loginbutton" for="u_0_7">
                        <input value="Log In" tabindex="4" type="submit" id="u_0_7">
                    </label>
                </td>
            </tr>
            <tr>
                <td class="login_form_label_field">
                    <div>
                        <div class="uiInputLabel clearfix">
                            <input id="persist_box" type="checkbox" name="persistent" value="1" checked="1" class="uiInputLabelCheckbox">
                            <label for="persist_box">Keep me logged in</label>
                        </div>
                        <input type="hidden" name="default_persistent" value="1">
                    </div>
                </td>
                <td class="login_form_label_field">
                    <a rel="nofollow" href="https://www.facebook.com/recover/initiate">Forgot your password?</a>
                </td>
            </tr>
        </tbody>
    </table>
    <input type="hidden" autocomplete="off" name="timezone" value="420" id="u_0_6">
    <input type="hidden" name="lgnrnd" value="225145_ZwaN">
    <input type="hidden" id="lgnjs" name="lgnjs" value="1381816305">
    <input type="hidden" autocomplete="off" id="locale" name="locale" value="en_US">
</form>
```

In this form, we have 10 different inputs (maybe other things are added in JS):

```
<input type="text" class="inputtext" name="email" id="email" value="" tabindex="1">
<input type="password" class="inputtext" name="pass" id="pass" tabindex="2">
<input value="Log In" tabindex="4" type="submit" id="u_0_7">
```

These are obvious.

```
<input id="persist_box" type="checkbox" name="persistent" value="1" checked="1" class="uiInputLabelCheckbox">
<input type="hidden" name="default_persistent" value="1">
```

As are those (how long should your session be).

```
<input type="hidden" autocomplete="off" name="timezone" value="420" id="u_0_6">
<input type="hidden" autocomplete="off" id="locale" name="locale" value="en_US">
```

These are throwaways (no meaningful).

```
<input type="hidden" id="lgnjs" name="lgnjs" value="1381816305">
```

That one is a timestamp, I assume it's used in JS somewhere (by the name).

```
<input type="hidden" name="lsd" value="AVq6TF4w" autocomplete="off">
<input type="hidden" name="lgnrnd" value="225145_ZwaN">
```

These two are mysterious.

From my very limited testing (deleting the hidden form fields and then signing in), it didn't seem to matter if they weren't there.

tl;dr POSTing is totally doable (which @apandhi already said while I was writing this answer, but I figured it was worth writing anyways).

I agree that we should store these offsite. What we can do is basically an API request on startup, which will load the latest configs (and a refresh button somewhere in the preferences to load the latest configs).

**Comment by apandhi** [comment]
What we can actually do is when they hit say, facebook, we just run $("input"), run through a foreach, and then just post that data using the username and password we want. This way we don't need to worry about hidden fields and such.

**Comment by jessepollak** [comment]
That'd work on the login page, but if we are elsewhere on the domain, that becomes trickier...

We could $.get(FACEBOOK_LOGIN_PAGE) and use those, but I'm pretty confident that they don't matter. 

We'll have to experiment. 

Who knows, maybe we'll find a security vulnerability or something fun :D

**Comment by josephwegner** [comment]
Alright, I fold.  It sounds like we're redefining what the Waltz experience should be, and I agree that it will rely on a more custom always-100%-working approach.

Once we start having custom site definitions, our feature options grow substantially.  I don't really want to talk about that yet, though, because I haven't begun to wrap my head around all of it.

The implementation of defining these site configurations is the most important part to me.  As of right now, I'm thinking the best way will be to have a Github repo, and allow users to put in pull requests with new configuration files (ie: google.com, amazon.com - these are separate JSON files).  On any commit/merge to master, we would use some continuous deployment service to build (concatenate) all of those JSON files, and upload it somewhere.  Perhaps an S3 bucket, perhaps to my or Clef's website.  Whatever - not important.  The extension will periodically poll that file to see if it has changed.

**Comment by jessepollak** [comment]
That could be cool.

**Comment by jessepollak** [comment]
I was also thinking that we could just have it as a YAML or JSON file in
the Waltz github repo...

Jesse Pollak
CPO at Clef
jesse@getclef.com

**Comment by jessepollak** [comment]
We went to defined, closing.
