### ISSUE TITLE
LinkedIn loggin failed

### ISSUE THREAD

**Issue by clawfire** [waltzio/waltz#344]
I want to add LinkedIn to waltz, Add email and password. I'm logged in linked in but the extension tell me I got invalid credentials ...

**Comment by landakram** [comment]
Hey @clawfire, would you give it another shot and let me know if you're still seeing the error? I've been using Waltz with LinkedIn with no issue when I log in from http://linkedin.com

**Comment by jessepollak** [comment]
I'm closing this as we can't replicate. @clawfire, please reopen if you can.
