### ISSUE TITLE
IRC Chat

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#35]
@lolux @jessepollak @zrathustra @brennenbyrne @landakram @apandhi 

We're setup with an IRC chat on Freenode.  #waltz

I'm working to get logs on it now.

**Comment by jessepollak** [comment]
#waltz is officially the coolest place in town. it's an awesome mix of @josephwegner and I missing each other as we each wish we had more time to do fun things in the giant playground that is waltz.

get on IRC and join us, y'all.

**Comment by josephwegner** [comment]
Logs are now up on botbot.me:

https://botbot.me/freenode/waltz/

That also means you can reference github tickets within IRC, using "gh#X" where X is the id of the ticket.

**Comment by jessepollak** [comment]
Sweet!
