### ISSUE TITLE
Valid SSL Cert

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#36]
Extension breaks if you haven't bypassed the ssl cert errors.  We should move to waltz.io, and get a real SSL cert probably

**Comment by jessepollak** [comment]
Yes, I will buy this soon.

Do we want to start with a clean server or use the one we've been using?

**Comment by josephwegner** [comment]
Uhh, it doesn't really matter to me.

If you do go to a new server, though, can you document the setup process?  I know there's that tutorial you sent me, but inevitably tutorials are never 100% accurate - I'd like to provide some waltz-specific instructions for people trying to setup their own Cy instance.

**Comment by jessepollak** [comment]
Just finished pushing to api.waltz.io with a valid SSL. Merged in changes that set api.waltz.io to the default cy server.
