### ISSUE TITLE
Explain what Cydoemus Is

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#37]
The first time you try to log into a site, you need to authenticate with Cydoemus.  Clef gives the message "Cydoemus is requesting that you sign up with Clef."

We should describe what Cydoemus is.

@jessepollak Any ideas on UX for this?  Probably just something on first run, but where the heck do we put it?

**Comment by jessepollak** [comment]
Cy should just be renamed to Vault and the Vault logo should be used as the image, yeah?

**Comment by josephwegner** [comment]
Cy === Waltz
