### ISSUE TITLE
Augmenter

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#4]

**Comment by jessepollak** [comment]
As I mention in another thread, I think that we want this to be something that, by default, there is a centrally hosted version of, but if a user chooses, they can host their own key server.

Just a heads up, I'm heading into the wilderness for 5 days, starting tomorrow midday, so I'll be out of contact for that period.

**Comment by josephwegner** [comment]
You said:

> Basically, the way I think this should happen is that there should be a central "vault server" (or whatever we call it), which will store all the encryption keys. However, if a user wants to, in an advanced options section of the plugin, they should be able to specify their own vault server...so anyone could host their own key server. Thoughts?

I think that's a good idea.  I think it may be worthwhile to break the augmentor out into a separate repo.  Both for cleanliness and because I think it could be useful in applications not specifically related to Clef.  ( _Oh boy, now I got myself wrapped up in making a cross-platform augmentor..  And writing it in Go.  I better stop thinking about it_ )

**Comment by jessepollak** [comment]
I agree.

**Comment by josephwegner** [comment]
OK,

Things are pretty much done until the augmenter is built.  The extension is encrypting, storing, retrieving, filling, yada yada yada - just need to grab the encryption keys from the augmenter.

I suppose I should have asked what stack you wanted to run it on, so that I could get started while you're on vacation.

**Comment by jessepollak** [comment]
Whoops, sorry!

So, at Clef, we're entirely Python/Flask/SQL; my stack of choice is Ruby/Sinatra/SQL, but I'd also be excited about trying something new. 

You mentioned Go, have you used it before? I've been meaning to and would love to give it a shot if you're up for it.

**Comment by josephwegner** [comment]
I've never used Go before, but am pretty determined to write one of my next few projects in it.  There's no technical reason that it would be good for the Augmenter (or, at least, better than anything else), but it would be fun to learn it.

I'm in.

Do you want me to create a separate repo, or you?

**Comment by jessepollak** [comment]
Just talked to @brennenbyrne and @landakram and we actually think we should
use a language we're all more familiar with because it's a security
sensitive application.

thoughts?

**Comment by josephwegner** [comment]
That sounds fine by me.  I'll use Go on another project :)

I'm generally a Node.js guy, but I do a lot of work in ruby these days.  Want to go with that?

**Comment by jessepollak** [comment]
I'm into going with Node. I haven't used it in awhile, but shouldn't be hard for me to pick back up. One question: I hear a lot about the problems with JS crypto; does this apply to Node as well?

**Comment by josephwegner** [comment]
I don't know of any issues with using crypto in Node.  The only reference I can find [is here](http://www.matasano.com/articles/javascript-cryptography/), but that's a pretty vague reference to an otherwise undocumented problem.  The crypto libraries are built into node, so they should be written in C++ and pretty safe.

I'll put together some scaffolding of an API.  I wrote a [simple api module](https://github.com/josephwegner/simple-api) awhile back that I've used and been quite pleased with.  It might need some updates to fully support what we want to do, but I think it will take out a lot of the scaffolding.

I generally use Mongo for my Node projects, but I'm thinking that that might not make as much sense since this is just a key value store.  Do you want to use MySQL, since that is what Clef uses?  Or Redis?

**Comment by jessepollak** [comment]
> I don't know of any issues with using crypto in Node. The only reference I can find is here, but that's a pretty vague reference to an otherwise undocumented problem. The crypto libraries are built into node, so they should be written in C++ and pretty safe.

Yeah, I figured it was mostly relegated to browser crypto.

> I'll put together some scaffolding of an API. I wrote a simple api module awhile back that I've used and been quite pleased with. It might need some updates to fully support what we want to do, but I think it will take out a lot of the scaffolding.

Sounds good to me. Github link?

> I generally use Mongo for my Node projects, but I'm thinking that that might not make as much sense since this is just a key value store. Do you want to use MySQL, since that is what Clef uses? Or Redis?

Let's think about what we need to make this work (this is in a MySQL-esque format, but I'm really not tied to that).
- User
  - clef_id
  - created_at
  - updated_at
  - other attributes

The User has_many encryption keys, one for each site.
- Encryption key
  - user_id
  - site domain
  - key
  - created_at
  - updated_at (in case we need to rotate or something)

Can you think of anything else?

**Comment by josephwegner** [comment]
Simple API Module: https://github.com/josephwegner/simple-api 
The documentation might not be super clear, so here's an example of a controller: https://github.com/josephwegner/css3man/blob/master/api/v0/controllers/men.coffee

For some reason I had it in my head that we were going to have to implement an OAuth server.  Thank goodness Clef does all the authentication junk for us :)

I think all that data works for me.  Though, now that I realize we're not doing OAuth, it doesn't really matter much which database structure we go with.  We're not really storing much.  I'll put scaffolding in tonight that uses Mongo.  If we want to change later on, it should be fairly simple.

I'm going to create a repo.  If we're going to have much more discussion, we should probably continue it there.
