### ISSUE TITLE
Switch out the spinning logo

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#40]
From the wise @lolux:

"The spinning Clef logo makes me think, "Is it doing something right now?" Usually, things that spin on computers and websites indicate the computer/server is working. The fast spinning that occurs when I'm supposed to insert credentials is a little dizzying."

I agree with this. I think it should be static (and probably Waltz).

**Comment by josephwegner** [comment]
Hah.  Good point.  Not sure how it took this long for that to come up :)

**Comment by josephwegner** [comment]
Done in rebrand branch
