### ISSUE TITLE
Waltz not working

### ISSUE THREAD

**Issue by RDCH106** [waltzio/waltz#408]
Waltz extension Chrome is not available in Chrome Web Store:

[https://chrome.google.com/webstore/detail/waltz/obhibkfopclldmnoohabnbimocpgdine](https://chrome.google.com/webstore/detail/waltz/obhibkfopclldmnoohabnbimocpgdine)

And It has stopped working my installed version in Chrome Browser.

**Comment by Gerzer** [comment]
I wish Waltz weren't neglected so much...

**Comment by jessepollak** [comment]
Hi y'all — thanks for the heads up, we're looking into it!

**Comment by jessepollak** [comment]
This has now been resolved.
