### ISSUE TITLE
Work on UI/UX of options

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#41]
Again, @lolux:

" I wasn't able to tell what the red and green dots did until I clicked on them to test them. The white thing in the green dot is too small for me to tell what it is."

I think the UX can improve as well, but making them bigger is a good first step.

**Comment by josephwegner** [comment]
I don't _love_ it, but I've changed the look a little bit in 4f1cdc8e31896da7b678ba433d8957bdbc348530.  Please reopen this and tell me what sucks about it, and I'll make it better.
