### ISSUE TITLE
Waltz doesn't show the barcode to access

### ISSUE THREAD

**Issue by RDCH106** [waltzio/waltz#415]
Two weeks ago (more or less) Waltz Chrome extension stopped showing the barcode that let to access to the pages configured to open them with Waltz.

**Comment by jessepollak** [comment]
Hi, you should have received an email — support for Waltz was discontinued on November 1st.

**Comment by RDCH106** [comment]
I am sad to hear that.

Sorry for the inconvenience and thanks for the years of support. @jessepollak, have you planned to continue someday?

**Comment by jessepollak** [comment]
We have no plans to continue with Waltz right now.
