### ISSUE TITLE
Add log out of all sites in options

### ISSUE THREAD

**Issue by apandhi** [waltzio/waltz#47]
It may be a nice idea to allow the user to be able to log out from their browser also as opposed to just the clef app

**Comment by josephwegner** [comment]
@jessepollak Security implications of this?  Would it be logging out of Clef, or just out of that current browser's sessions?

**Comment by jessepollak** [comment]
Take back my seconded. If we log the user out of the browser, it wouldn't _feel_ like they'd been logged out because they'd still be logged into Clef.

Don't think this will work.

**Comment by apandhi** [comment]
Hm care to elaborate a bit on why it wouldn't feel like they logged out?

Couldn't we just send an HTTP Get request to https://clef.io/api/v1/user/global_logout to log them out?

**Comment by jessepollak** [comment]
Yes, we could, but that would live the user still logged in on the phone even though their computer session had been terminated.

**Comment by josephwegner** [comment]
Wahh??  Does that endpoint actually exist?  Does Clef have real API documentation on stuff like that?

**Comment by jessepollak** [comment]
That API does actually exist, but no, it's no documented.

It's actually a temporary solution we have for letting people who don't get
the "log out on your phone" thing to log out on their computers from
getclef.com.

Sooner or later it will be replaced.

**Comment by josephwegner** [comment]
@jessepollak So, is it reasonable to assume that an endpoint like `global_logout` will always exist?  Can we build a feature around that?

Or should we continue this discussion without that endpoint as an option?

**Comment by jessepollak** [comment]
No, let's not assume that will always exist.

**Comment by landakram** [comment]
I think this encourages people to just log out in their browsers, instead of understanding that they can log out from the entire session from their phone. 

To that end, I don't think we should implement this—I think it will cause confusion among users who log out on their browser, click the waltz button, and then are concerned that they didn't have to resync with their phone.
