### ISSUE TITLE
License

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#5]
How is this going to work?

The repo is owned my Clef - does that mean the source belongs to Clef?  Is it open source?  Do the rights/attribution go to me, or Clef?  Or are we doing some sort of dual license?  Will we eventually be making this repo public (allowing me and others to fork it)?

If a year from now we have a falling out about the extension, am I free to take the code and run? (not that I foresee that happening)

**Comment by jessepollak** [comment]
We should just go with your OSS license of choosing, as lenient as possible. Definitely no ownership by Clef; attribution can go to anyone who helps out.

Yes, the repo should definitely be made public. I just want to get something solid before we do that (especially with crypto code etc). 

Hopefully no falling outs :D but yes, most certainly.

Basically, the way I think this should happen is that there should be a central "vault server" (or whatever we call it), which will store all the encryption keys. However, if a user wants to, in an advanced options section of the plugin, they should be able to specify their own vault server...so anyone could host their own key server. Thoughts?

**Comment by josephwegner** [comment]
OK - I'm just going to got with [MIT](http://choosealicense.com/licenses/mit/), unless you care.

I will respond to the second half in the other comment thread, where it is more appropriate.
