### ISSUE TITLE
Site Configs and Travis CI

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#51]
Hello all (@waltzio/owners),

Waltz is now setup for defined site configs.  You will notice a new folder called site_configs in the repository root, which has some JSON files in it.  The contents of those files are crap at this point, but what they _mean_ is important.  They mean that from now on, new sites can simply be added by creating a new JSON file in that folder.

To do this, Waltz is now using Travis CI.  Travis is notified every time there is a commit on master, at which point it concatenates all the JSON site configs into one file and updates the file in the repo (deploy/site_configs.json).  This file will be accessed directly from the extension, from that raw.github.com endpoint.

The implication of this is that we don't want Travis to be building and committing every time we push a change.  That means **all** work needs to be done on feature branches, and **merged into develop**.  When we're ready for a release, that will be merged into master, probably via a pull request.  This is actually very good version management, so we should have been doing this from the start.

I have created a develop branch for you to start working on.  Please don't touch master anymore, unless you have some good reason.

**Comment by apandhi** [comment]
Ah this seems awesome. But what are the implications of using raw.github.com? I feel like that would be frowned upon most of the time.

That being said, what are the plans for putting sites and configuring it?

**Comment by josephwegner** [comment]
@apandhi 

I agree, it's not a 100% awesome idea to utilize raw.github.com.  The reasoning behind that is mostly that I don't want to pay to upload those site configs anywhere, and I don't want Clef to host them (for ownership reasons).

I think once we get waltzio.com up and running, I will update Travis to send the configs there.  That way we also don't dirty up the commit history on master.

I don't know exactly the format or even the contents of the site configs yet, but I think it'll just be a few items to start with:
- Domains support (*.google.com or just accounts.google.com?)
- Authentication Session Cookie (for logging out)
- URL for POSTing to login
- Other keys/endpoints that may be required for logging in

**Comment by apandhi** [comment]
There are a few things I think we need for site configs along with those.

A callback function to check if the user logged in or if it failed (Can be a string that we eval into javascript)
and a function that runs on page load so we can scrape the form elements we need other than just the username and password. 

The callback function seems most important to me right now so we can properly save credentials

**Comment by jessepollak** [comment]
For checking if the user is logged in, we can just look if the authentication cookie is set.

**Comment by jessepollak** [comment]
We have a defined schema in the site_configs folder as of the latest pull into master, so I'm going to close this for now. It may adapt as we add more sites.
