### ISSUE TITLE
Move waltz to browser icon instead of appending on every page

### ISSUE THREAD

**Issue by apandhi** [waltzio/waltz#53]
After using waltz for over a week, the major problem with it is that it constantly appends the waltz icon on every site even if I don't want to log into that site.

**Comment by josephwegner** [comment]
@apandhi The only trouble with moving waltz to the browser icon, is pretty soon Waltz will not be applicable to every page.  We _could_ have it open up the options page if Waltz isn't configured for that page, but we're trying to minimize interaction with the options page.

I'm playing around with ideas for the dismiss button. I think I will enable some to either "dismiss once" or "dismiss for this session".  Then it won't show up on your current site for some amount of time.

Would this solve your annoyance, or is the problem deeper than that?

**Comment by jessepollak** [comment]
I think that this will be partially addressed when we move to the per-site configs. This way, it will only pop up on places where it works.

**Comment by ahrussell** [comment]
Wouldn't it make sense to have it pop up places where it doesn't work, so
that we can track where people are trying to use it most, and then
prioritize adding those sites?

**Comment by josephwegner** [comment]
Can you guys try out the most recent version of the extension, and see if you still think this is an issue?

I think it's mostly out of scope now that we're using site-specific configs, but I'm open to discussion about it.  Otherwise, I'd like to close this.

**Comment by josephwegner** [comment]
I'm closing this, because I don't think it applies anymore.  Feel free to reopen.
