### ISSUE TITLE
User should be redirected to page they started on

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#58]

**Comment by jessepollak** [comment]
On backend, capture the page you are on when login is submitted.

If that page is login page, proceed as normal.

If that page is different than login page, _after POST to login_, redirect on the backend back to the page you started on.

**Comment by landakram** [comment]
https://github.com/waltzio/waltz/pull/88

**Comment by jessepollak** [comment]
I'm closing this as we have a PR that adds this feature.
