### ISSUE TITLE
Switch out way sessions are handled in simple-api

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#64]
@josephwegner I wasn't sure whether to put this in here or in the simple-api repo.

We need to switch out the in-memory session handle used by simple-api. Primarily, this is an issue because every time we deploy we lose all of our session data (i.e. every user is logged out of everything).

How should we proceed?

**Comment by jessepollak** [comment]
NVM, this isn't in simple-api, it's node-session.

**Comment by jessepollak** [comment]
This is fixed, but deploys are no longer working :/

**Comment by josephwegner** [comment]
Alright, @jessepollak, I'm digging into the server issues now.  Hopefully I can get us back up by tomorrow.

**Comment by jessepollak** [comment]
Just pushed the latest version of this that works :)
