### ISSUE TITLE
Local Storage or Sync Storage

### ISSUE THREAD

**Issue by josephwegner** [waltzio/waltz#7]
Chrome has something called "sync storage".  Essentially, it's a version of the HTML5 storage mechanism that gets synced across computers running chrome under your user account.

I'm tempted to use the sync storage for storing credentials.  The idea behind a password manager is that it will remember your passwords, which often leads to forgetting passwords.  Chrome sync would solve that.

However, using sync would also add the GMail account - as well as all computers that sync to that account - as an intrusion point.

For now I'll use local storage, but would like to hear other thoughts on this.

**Comment by landakram** [comment]
I don't like the idea of tying things/requiring a GMail account, since I don't even log in to GMail when I use Chrome. Syncing the credentials is tempting though, so we should keep that in mind for the future.

I say we stick with local storage for now.

**Comment by landakram** [comment]
Also, if people run an augmenter locally (would they?) then the synced credentials wouldn't work. They'd need to run an augmenter elsewhere or use the central one. Just something to think about.

**Comment by josephwegner** [comment]
Right - I don't believe a google account is required in order to use sync storage (it just wouldn't sync).  That's a good point about the augmenter, though.  If people ask for that feature down the road, we should probably make it opt-in so that nothing gets overwritten.

**Comment by jessepollak** [comment]
I agree on sticking with localStorage for now.

Does mobile chrome have extensions?

**Comment by josephwegner** [comment]
No, chrome mobile [does not support extensions](https://developers.google.com/chrome/mobile/docs/faq).

Local it is.  Closing this.

**Comment by bgiesing** [comment]
Is there anyway this could be considered again? I use almost a different computer every day and what is the point of password-less login, if we have to set it up everyday.
