### ISSUE TITLE
Decide on standardized key to store credentials under

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#72]
Right now, we store credentials under the top level key for the domain. This is the http://_.facebook.com/_ format.

This freaks me out. I can imagine a situation where this would change and then we'd basically kill all of a users saved credentials.

Are we comfortable with sticking with this or should we decide on another standardized key?

Thoughts much appreciated.

**Comment by lolux** [comment]
(Ignore this if I'm not understanding what you're asking here . . . this
may not relate to the key question directly.)

In my experience with LP it has been useful in several instances to be able
to define URLs that are synonymous (i.e., that share the same login
credential) both (a) between a TLD and its subdomains and (b) between two
or more different TLDs. LP calls these "equivalent domains" and preloads a
default list and gives the option to add your own entries.

For example: apple.com, itunes.com, and icloud.com share the same
credential.

**Comment by jessepollak** [comment]
That's another reason to do this, so we could tie things like youtube.com and google.com together.

**Comment by jessepollak** [comment]
This is addressed in #74. allows for aliasing like Laurence talks about.
