### ISSUE TITLE
Submit credentials through form if on login page

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#73]
OK, so a couple of times I've had this occur:
1. Try to log in to Google.
2. It won't accept my credentials and takes me to a page to "retype my password"
3. Waltz won't work

I'm not sure why this happens, but I think that we can avoid this by submitting the credentials through the form if we are on the login page. I know this takes away a little bit of the "magic," but it also might make it much more reliable.

Thoughts?

**Comment by josephwegner** [comment]
That seems like a fine solution for now, but I'd be more interested in knowing why this happens.

**Comment by jessepollak** [comment]
Me too :/
