### ISSUE TITLE
Repeated Logout Notifications

### ISSUE THREAD

**Issue by iamb55** [waltzio/waltz#79]
Whenever I wake my computer up from sleep I get about 10 notifications from Waltz telling me that I've been logged out. This happened over the course of several days where I wasn't using Waltz at all in between sessions. 

Just now, my Clef timer ran out and I was logged out of Clef. I got between 50-100 logout notifications.

**Comment by jessepollak** [comment]
This is intended functionality... 

;)

will fix.

**Comment by jessepollak** [comment]
This is fixed in cd7eb6cf46c896401581441b2dc45a0166c91eee.
