### ISSUE TITLE
aes.js is missing

### ISSUE THREAD

**Issue by jessepollak** [waltzio/waltz#8]
Not sure what's going on here, I think we're just missing the cryptojs dependency.

![screen shot 2013-08-22 at 6 58 03 am](https://f.cloud.github.com/assets/1097953/1009098/f2612064-0b32-11e3-911b-d9a4e51427aa.png)

ps. I'm back!

**Comment by jessepollak** [comment]
Added aes.js from cryptojs in 72d9e4f. Not 100% sure whether this is the correct implementation, got it from [here](https://code.google.com/p/crypto-js/downloads/list). 

@josephwegner please confirm and close.

**Comment by josephwegner** [comment]
Whoops.  I have a bad habit of forgetting to `git add` everything.  My bad!

That file you added will work.

Welcome back - hope your vacation was great!

**Comment by jessepollak** [comment]
Still needed core.js from CryptoJS, I put all the CryptoJS code in one file and reorganized the vendor javascript into a separate folder in 9dc25b5.

The vacation was awesome; saw a bear, caught and ate some fish, all the good stuff.

**Comment by jessepollak** [comment]
Was still broken; realized there was a rolled up version of aes.js that you'd probably been using.

Fixed in 66a7cfb.

**Comment by josephwegner** [comment]
Inside of [that zip](https://code.google.com/p/crypto-js/downloads/list) there is a folder called "rollups".  Those are each encryption method rolled up with the core.  If what you did works just as well, that's fine, but if you run into more issues that rollup should work.  That's what I was using on my local.

(odd that when I pulled your last commit down it still worked...  Not sure what the deal on that is)

**Comment by jessepollak** [comment]
see above :D
