### ISSUE TITLE
Clef overlay never appears

### ISSUE THREAD

**Issue by landakram** [waltzio/waltz#99]
Steps to reproduce:
1. Delete Waltz and start from a fresh install, logged out of Clef, cookies cleared
2. Go to facebook.com
3. Click the Waltz icon

Result: 
Clef overlay never appears and there is an error in the console: 

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://api.waltz.io') does not match the recipient window's origin ('https://clef.io').
```

This seems to only happen when I have just cleared my cookies, cache, and saved data.

**Comment by jessepollak** [comment]
Fixed in waltzio/cy@664e5caf690b71ce98f2dee840f445812f32ed96.
